### ISSUE TITLE
nightwatch tests are broken

### ISSUE THREAD

**Issue by dwhitecl** [CMSgov/macpro-quickstart-serverless#193]
## Type of Issue:

- [x] Bug: Something isn't working

#### Issue Creator Checklist

- [x ] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## What's broken?
Currently nightwatch tests are broken in all environments with the following error.

![Screen Shot 2021-04-26 at 8 59 56 AM](https://user-images.githubusercontent.com/52459927/116086501-e1826f80-a66d-11eb-837c-ff37f9156eef.png)

## What's the impact of this bug?

Nightwatch tests fail in every environment and result in a "red" build

## Steps to Reproduce?

Create a new branch off of master and push, or re-run the master deploy job.

## AC:

The issue is resolved and the nightwatch testing suite will run through cleanly.

**Comment by joeaero19** [comment]
The test is failing because the chromedriver version (88) and the chrome browser version (currently 90) does not match. The version difference could be because the runnings got updated and the browser versions got upgraded from 88 to 90. To fix this I upgraded the chromedriver version to 90 as well. The test is running smoothly.
