### ISSUE TITLE
Create a wiki page within the repo with Okta instructions 

### ISSUE THREAD

**Issue by dwhitecl** [CMSgov/macpro-quickstart-serverless#205]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

We should create a wiki page for consumers of the quickstart with instructions of exactly what they need to do to get their app integrated with okta... from requesting the okta instance itself, job codes, ssm params, to actual code changes 

This documentation should specifically include an explanation of how to bypass the hosted ui altogether when wired to Okta.  This was discussed in #202 but can be more thoroughly documented in the wiki.  In short... if you'd like environments that are wired to Okta to disable the direct Cognito login, you can, with a small code change.  We didn't make that change here, as we always want anybody to be able to test drive the app, even if they're not in Okta.  But we expect other projects will want "turn on okta" to also indicate "turn off direct cognito signup/login". 

## Proposed Approach

This documentation should leverage the GitHub native [wiki for macpro-quickstart-serverless](https://github.com/CMSgov/macpro-quickstart-serverless/wiki).
The wiki is in a near hello world state, so there's a lot of freedom to choose how things look and are organized.  Do what you think is best.

## Value

Clear instructions on how to integrate with Okta, if desired, will help consumer's of this repo get their project's off the ground faster, with less of a reliance on the authors of the okta integration.

## AC:

- Appropriate details and notes on the optional Okta integration added by #202 are detailed in the GitHub wiki.
- Instructions on how to configure an environment to use Okta are added to the wiki.

**Comment by dwhitecl** [comment]
another thing to specifically document is the "okta + signup" functionality that exists in the quickstart. We should explain this, why we did this, and what teams should probably do with that after they fork ... i.e. get rid of the sign up workflow when wired to an okta environment.

**Comment by mdial89f** [comment]
@dwhitecl we spoke in a side chat about this, just logging for history here.
I added a lot of content to the wiki.  It's laid out in three main sections:
- Design:  this is meant to detail components of the application, detail design decisions, and explain how to extend stuff.  This is very conceptual and high level.  This has NOT been fleshed out for this issue, but a placeholder has been made.
- How-To:  this is the meat of the step by step in the wiki.  It's meant to be very verbose and specific.  
- Workflows:  this is meant to be, basically, higher level How-tos.  A workflow can link to many different how-tos.  In this case there's only one new workflow, which is creating a new environment backed by okta.  I imagine this sectipno will expand with things like "Setting up your mac", "Deleting an environment manually", etc.  

Not all of the above is directly related to this issue, but it's where my heads at, at the moment.  

I feel this is close to the point of diminshing returns; I've captured the how-to details in the wiki.
This is akward to review since we can't PR the wiki.  Ready for eyes on it though.
