### ISSUE TITLE
Add backup strategy to Dynamo

### ISSUE THREAD

**Issue by dwhitecl** [CMSgov/macpro-quickstart-serverless#284]
## Type of Issue:

- [x] Enhancement: New feature or request

#### Issue Creator Checklist

- [x] This issue has been thoroughly documented below; a developer should be able to understand the issue by reading it.

## Background

Currently Dynamo is not configured to run any sort of backups or retention. Given that most government project have this as a requirement this would be a good capability to build in, not just for government projects but good practice in general.

## Proposed Approach

A solution has been pushed to the Seds repo. Review the solution and see what is applicable to be pulled into the quickstart. 
Link to the PR: 
https://github.com/CMSgov/cms-mdct-seds/pull/322
Consider this option:
https://aws.amazon.com/dynamodb/pitr/

Confirm with Eric what a required retention period for a production DB is.

## Value

Out of the box Dynamo backup strategy allowing projects to be data retention compliant 

## AC:

Dynamo will be set up to be backed up and backups retained each at a configurable value
Environments that are backed up will be configurable, dev environments should not be backed up and retained.

**Comment by joeaero19** [comment]
This issue was resolved by setting up an ssm parameter for val,prod and master to true and default to false.  Point-in-time-recovery was set to true for val,prod and master and set to false for all other environments.
PR has been created and review has been requested.

PR: https://github.com/CMSgov/macpro-quickstart-serverless/pull/287
